### ISSUE TITLE
Locking a key on Redis

### ISSUE THREAD

**Issue by neographikal** [andrew-bn/RedisBoost#2]
Hi, 

Sorry, another question, is there an easy way to lock a key/value pair on Redis with Redisboost? I don't see it in the API but for me it is useful in a couple of situations.

Thanks!

**Comment by andrew-bn** [comment]
Currently RedisBoost implements only Redis API set. But you can look at recomended implementations of Lock for C# on Redis.io (http://redis.io/topics/distlock) .
